package:
  name: kivy
  version: "1.9.1"

source:
  git_url: https://github.com/janssen/kivy.git
  git_tag: stable

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - cython ==0.21.2

  run:
    - python
    - setuptools

test:

about:
  home: https://github.com/janssen/kivy
  license: MIT
  summary: 'fork of Kivy repo with some minor fixes'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
